# Generated by Django 3.0.6 on 2020-05-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmingfield',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='qanda',
            old_name='url',
            new_name='link',
        ),
    ]
