# Generated by Django 3.0.6 on 2020-05-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200526_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingfield',
            name='link',
        ),
        migrations.RemoveField(
            model_name='qanda',
            name='link',
        ),
    ]
