# Generated by Django 3.0.6 on 2020-05-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200526_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingfield',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmingfield',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qanda',
            name='answer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qanda',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
