# Generated by Django 3.0.6 on 2020-05-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200526_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingfield',
            name='description',
            field=models.TextField(),
        ),
    ]
