# Generated by Django 3.0.6 on 2020-05-27 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200526_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('link', models.URLField()),
                ('question_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
