# Generated by Django 2.2.10 on 2020-06-03 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('link', models.URLField()),
                ('question_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
